[workspace]
resolver = "1"
members = [
    "agent",
    "common",
]
default-members = [
    "agent",
]

[workspace.dependencies]
kube = { version = "2.0.1", features = ["runtime", "client", "derive"] }
k8s-openapi = { version = "0.26.0", features = ["latest", "schemars"], default-features = false }

tracing = "0.1.37"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.143"
rust-yaml = { git = "https://github.com/sebt3/rust-yaml", branch = "main" }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
chrono = { version = "0.4.38", features = ["serde"] }
schemars = { version = "1.0", features = ["chrono04"] }
actix-web = "4.12.1"
base64 = "0.22.1"

[workspace.package]
version = "0.5.8"
authors = ["SÃ©bastien Huss <sebastien.huss@gmail.com>"]
edition = "2024"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "vynil"
publish = false
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

