[package]
name = "package"
version = "0.2.1"
authors = ["SÃ©bastien Huss <sebastien.huss@gmail.com>"]
edition = "2021"
license = "	BSD-3-Clause"

[dependencies]
anyhow = "1.0.69"
rhai = { version = "1.12.0", features = ["serde"] }
serde =  { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.17"
log = "0.4.17"
regex = "1.7.3"
openapiv3 = "1.0.2"
indexmap = "1.9.3"
serde_json = "1.0.95"
handlebars = "4.3.6"
schemars = { version = "0.8.11", features = ["chrono"] }

[lib]
name = "package"
path = "src/lib.rs"
